config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get '/about' => 'pages#about', as: :about
  get '/home' => 'pages#home', as: :home

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def about

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Castoro&display=swap" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
    <h2>Kristina Radojevic</h2>
    <div class="topnav">
      <a class="active" href="#home"><%= link_to "Home page", home_path %></a>
      <a href="#news"><%= link_to "About page", about_path %></a>
    </div>
  </header>
<%= yield %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/about.html.erb
<html>

<body>
  <section class="section">
    <h4> About page </h4>
  </section>
  <article class="article">
    <h4>Subheading</h4>
    <button>Signup<button>
  </article>
</body>

</html>

app/views/pages/home.html.erb
<html>

<body>
  <section class="section">
    <button>Learn more</button>
  </section>
  <article class="article">
    <h4>Subheading</h4>
  </article>
  <aside>
    <h4>Subheading</h4>
    <button><%= link_to "Learn more", about_path %></button>
  </aside>
  <footer>
  </footer>
</body>

</html>